services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db # IMPORTANT: Create a PostgreSQL DB on Render named 'portfolio-db'
          property: connectionString
