services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: development
